package ads

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strconv"
	"strings"
)

// FormatGeneratedCode assembles declarations into a standalone Go source file.
func FormatGeneratedCode(typeCodes []string, pkg string) (string, error) {
	if !token.IsIdentifier(pkg) || token.Lookup(pkg).IsKeyword() {
		return "", fmt.Errorf("invalid package name %q", pkg)
	}
	body := "package " + pkg + "\n" + strings.Join(typeCodes, "\n")
	f, err := parser.ParseFile(token.NewFileSet(), "generated.go", body, 0)
	if err != nil {
		return "", err
	}
	imports := map[string]string{}
	ast.Inspect(f, func(node ast.Node) bool {
		if sel, ok := node.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				switch id.Name {
				case "ads":
					imports["ads"] = "github.com/fluxin/go-native-ads"
				case "context":
					imports["context"] = "context"
				case "time":
					imports["time"] = "time"
				}
			}
		}
		return true
	})
	names := map[string]bool{}
	methods := map[string]bool{}
	for _, decl := range f.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok {
			key := fn.Name.Name
			if fn.Recv != nil {
				var recv strings.Builder
				if err := format.Node(&recv, token.NewFileSet(), fn.Recv.List[0].Type); err != nil {
					return "", err
				}
				key = strings.TrimPrefix(recv.String(), "*") + "." + key
				if methods[key] {
					return "", fmt.Errorf("generated method collision: %s", key)
				}
				methods[key] = true
			} else {
				if names[key] {
					return "", fmt.Errorf("generated name collision: %s", key)
				}
				names[key] = true
			}
			continue
		}
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			var ids []*ast.Ident
			switch spec := spec.(type) {
			case *ast.TypeSpec:
				ids = []*ast.Ident{spec.Name}
			case *ast.ValueSpec:
				ids = spec.Names
			}
			for _, id := range ids {
				if names[id.Name] {
					return "", fmt.Errorf("generated name collision: %s", id.Name)
				}
				names[id.Name] = true
			}
		}
	}
	var fieldErr error
	ast.Inspect(f, func(node ast.Node) bool {
		st, ok := node.(*ast.StructType)
		if !ok {
			return true
		}
		seen := map[string]bool{}
		for _, field := range st.Fields.List {
			for _, name := range field.Names {
				if seen[name.Name] {
					fieldErr = fmt.Errorf("generated field collision: %s", name.Name)
				}
				seen[name.Name] = true
			}
		}
		return true
	})
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				for _, name := range field.Names {
					if methods[ts.Name.Name+"."+name.Name] {
						return "", fmt.Errorf("generated field/method collision: %s.%s", ts.Name.Name, name.Name)
					}
				}
			}
		}
	}
	for alias := range imports {
		if names[alias] {
			return "", fmt.Errorf("generated name shadows import %s", alias)
		}
	}
	if fieldErr != nil {
		return "", fieldErr
	}
	var out strings.Builder
	out.WriteString("// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.\n\npackage " + pkg + "\n")
	keys := make([]string, 0, len(imports))
	for key := range imports {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		out.WriteString("import " + key + " " + strconv.Quote(imports[key]) + "\n")
	}
	out.WriteString(strings.Join(typeCodes, "\n"))
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return "", err
	}
	return string(formatted), nil
}
