// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.

package main

import ads "github.com/fluxin/go-native-ads"
import context "context"

type RPCClientAddInput struct {
	A ads.Int16 "ads:\"a\""
	B ads.Int16 "ads:\"b\""
}
type RPCClientAddResult struct {
	// PLC return value
	ReturnValue ads.Int16 "ads:\"$return\""
}
type RPCClientPingInput struct {
}
type RPCClientPingResult struct {
}

// RPCClient is a typed PLC RPC client. Calls are never retried automatically.
type RPCClient struct {
	rpc0 *ads.RPC[RPCClientAddInput, RPCClientAddResult]
	rpc1 *ads.RPC[RPCClientPingInput, RPCClientPingResult]
}

// NewRPCClient binds an instance and verifies its generated method signatures.
func NewRPCClient(conn *ads.Connection, instance string) (*RPCClient, error) {
	r := new(RPCClient)
	var err error
	r.rpc0, err = conn.BindRPC[RPCClientAddInput, RPCClientAddResult](instance, "Add", ads.RPCOptions{Signature: "c8527450112b1269d762f6b6ef0d714fc03223b896ee3b736eb29a6582f47eff"})
	if err != nil {
		return nil, err
	}
	r.rpc1, err = conn.BindRPC[RPCClientPingInput, RPCClientPingResult](instance, "Ping", ads.RPCOptions{Signature: "83efb8407241abdc3deec868d96a5a49ec3344ca725a4a8f88b3f94c21a3a916"})
	if err != nil {
		return nil, err
	}
	return r, nil
}

// Add calls PLC method Add.
func (c *RPCClient) Add(ctx context.Context, input RPCClientAddInput) (RPCClientAddResult, error) {
	return c.rpc0.Call(ctx, input)
}

// Ping calls PLC method Ping.
func (c *RPCClient) Ping(ctx context.Context) error {
	_, err := c.rpc1.Call(ctx, RPCClientPingInput{})
	return err
}
