// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.

package main

import ads "github.com/fluxin/go-native-ads"
import context "context"

type ReferenceClientFillBufferInput struct {
	Count ads.Uint16 "ads:\"count\""
}
type ReferenceClientFillBufferResult struct {
	// Length in elements is set by input count.
	Values []ads.Int16 "ads:\"values\""
}
type ReferenceClientIncrementInput struct {
	Value ads.Int32 "ads:\"value\""
}
type ReferenceClientIncrementResult struct {
	Value ads.Int32 "ads:\"value\""
}
type ReferenceClientSumBufferInput struct {
	Count ads.Uint16 "ads:\"count\""
	// Length in elements is set by input count.
	Values []ads.Int16 "ads:\"values\""
}
type ReferenceClientSumBufferResult struct {
	// PLC return value
	ReturnValue ads.Int32 "ads:\"$return\""
}

// ReferenceClient is a typed PLC RPC client. Calls are never retried automatically.
type ReferenceClient struct {
	rpc0 *ads.RPC[ReferenceClientFillBufferInput, ReferenceClientFillBufferResult]
	rpc1 *ads.RPC[ReferenceClientIncrementInput, ReferenceClientIncrementResult]
	rpc2 *ads.RPC[ReferenceClientSumBufferInput, ReferenceClientSumBufferResult]
}

// NewReferenceClient binds an instance and verifies its generated method signatures.
func NewReferenceClient(conn *ads.Connection, instance string) (*ReferenceClient, error) {
	r := new(ReferenceClient)
	var err error
	r.rpc0, err = conn.BindRPC[ReferenceClientFillBufferInput, ReferenceClientFillBufferResult](instance, "FillBuffer", ads.RPCOptions{Signature: "7c0922c7bc7ef1ebbd707f6b6a8d06c0d886b5d9534f0f346f8975ffae433ad7"})
	if err != nil {
		return nil, err
	}
	r.rpc1, err = conn.BindRPC[ReferenceClientIncrementInput, ReferenceClientIncrementResult](instance, "Increment", ads.RPCOptions{Signature: "6132c53005e1004101c6c836ee3cec6d2fbd7d0bc3c1973ee391dd8b8f10f135"})
	if err != nil {
		return nil, err
	}
	r.rpc2, err = conn.BindRPC[ReferenceClientSumBufferInput, ReferenceClientSumBufferResult](instance, "SumBuffer", ads.RPCOptions{Signature: "f37b96fe045ac16d08c3434821c9963ccde3346f250f2c545ea6d4f3dc8ec722"})
	if err != nil {
		return nil, err
	}
	return r, nil
}

// FillBuffer calls PLC method FillBuffer.
func (c *ReferenceClient) FillBuffer(ctx context.Context, input ReferenceClientFillBufferInput) (ReferenceClientFillBufferResult, error) {
	return c.rpc0.Call(ctx, input)
}

// Increment calls PLC method Increment.
func (c *ReferenceClient) Increment(ctx context.Context, input ReferenceClientIncrementInput) (ReferenceClientIncrementResult, error) {
	return c.rpc1.Call(ctx, input)
}

// SumBuffer calls PLC method SumBuffer.
func (c *ReferenceClient) SumBuffer(ctx context.Context, input ReferenceClientSumBufferInput) (ReferenceClientSumBufferResult, error) {
	return c.rpc2.Call(ctx, input)
}
