package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"sort"
	"strings"

	ads "codeberg.org/fluxin/go-native-ads"
)

func init() {
	handler := slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	})
	slog.SetDefault(slog.New(handler))
}

var (
	ip          = flag.String("ip", "127.0.0.1", "the address to the AMS router")
	netid       = flag.String("netid", "199.4.42.250.1.1", "AMS NetID of the target")
	port        = flag.Int("port", 48898, "AMS Port of the target")
	localNetid  = flag.String("localNetId", "172.30.0.2.1.1", "AMS NetID of the local")
	localPort   = flag.Int("localPort", 10500, "AMS Port of the local")
	output      = flag.String("o", "generated_types.go", "Output file for generated Go code")
	symbols     = flag.String("symbols", "", "Comma-separated list of symbols to generate (e.g., MAIN.i,MAIN.b,MAIN.eeks)")
	packageName = flag.String("pkg", "main", "Package name for generated code")
)

func main() {
	flag.Parse()

	if *symbols == "" {
		fmt.Println("Usage: go run . -symbols=MAIN.i,MAIN.b,MAIN.eeks")
		fmt.Println("  -symbols: Comma-separated list of TwinCAT symbols")
		fmt.Println("  -o: Output file (default: generated_types.go)")
		fmt.Println("  -pkg: Package name (default: main)")
		os.Exit(1)
	}

	fmt.Printf("TwinCAT Go Code Generator\n")
	fmt.Printf("========================\n\n")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	connection, err := ads.NewConnection(ctx, *ip, *port, *netid, 851, *localNetid, *localPort, false, ads.DefaultReconnectPolicy())
	if err != nil {
		slog.Error("Failed to create connection", "error", err)
		os.Exit(1)
	}

	err = connection.Connect()
	if err != nil {
		slog.Error("Failed to connect", "error", err)
		os.Exit(1)
	}
	defer connection.Close()

	// Parse symbol list
	symbolList := strings.Split(*symbols, ",")
	for i := range symbolList {
		symbolList[i] = strings.TrimSpace(symbolList[i])
	}

	fmt.Printf("Analyzing %d symbols...\n\n", len(symbolList))

	// Generate types for each symbol
	var generatedTypes []string
	enumTypeNames := map[string]bool{}
	for _, symName := range symbolList {
		code, err := connection.GenerateType(symName)
		if err != nil {
			slog.Error("Failed to generate type", "symbol", symName, "error", err)
			continue
		}
		generatedTypes = append(generatedTypes, code)
		collectEnumTypeCandidates(connection, symName, enumTypeNames)

		// Get info for display
		info, err := connection.AnalyzeType(symName)
		if err == nil {
			fmt.Printf("✓ %s: %s -> %s\n", symName, info.Type, info.GoType)
		}
	}

	if len(generatedTypes) == 0 {
		slog.Error("No symbols to generate")
		os.Exit(1)
	}

	for typeName := range enumTypeNames {
		enumCode, err := generateEnumCode(connection, typeName)
		if err != nil {
			continue
		}
		generatedTypes = append(generatedTypes, enumCode)
	}

	// Generate Go code
	fmt.Printf("\nGenerating Go code...\n")
	code := generateGoCode(generatedTypes, *packageName)

	// Write output file
	err = os.WriteFile(*output, []byte(code), 0o644)
	if err != nil {
		slog.Error("Failed to write output file", "error", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Generated %s with %d types\n", *output, len(generatedTypes))
}

func generateGoCode(typeCodes []string, pkg string) string {
	var builder strings.Builder

	builder.WriteString("// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.\n")
	builder.WriteString("// Source: TwinCAT PLC symbols\n\n")
	builder.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	// Write all generated types
	for _, typeCode := range typeCodes {
		builder.WriteString(typeCode)
		builder.WriteString("\n")
	}

	return builder.String()
}

func collectEnumTypeCandidates(conn *ads.Connection, symbolName string, out map[string]bool) {
	symbol, err := conn.GetSymbol(symbolName)
	if err != nil {
		return
	}
	collectSymbolDataTypes(symbol, out)
}

func collectSymbolDataTypes(symbol *ads.Symbol, out map[string]bool) {
	out[symbol.DataType] = true
	for _, child := range symbol.Children {
		collectSymbolDataTypes(child, out)
	}
}

func generateEnumCode(conn *ads.Connection, typeName string) (string, error) {
	enumInfo, err := conn.GetEnum(typeName)
	if err != nil {
		return "", err
	}
	goType := ads.Registry.GetGoType(enumInfo.BaseType)
	if goType == "interface{}" {
		return "", fmt.Errorf("unsupported enum base type %s", enumInfo.BaseType)
	}

	goTypeName := goName(enumInfo.Name)
	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("// %s represents TwinCAT enum %s\n", goTypeName, enumInfo.Name))
	builder.WriteString(fmt.Sprintf("type %s %s\n\n", goTypeName, goType))
	builder.WriteString("const (\n")
	for _, name := range sortedEnumNames(enumInfo.Values) {
		builder.WriteString(fmt.Sprintf("\t%s %s = %d\n", enumMemberConstName(goTypeName, name), goTypeName, enumInfo.Values[name]))
	}
	builder.WriteString(")\n")
	return builder.String(), nil
}

func enumMemberConstName(enumTypeName string, memberName string) string {
	return fmt.Sprintf("%s_%s", enumTypeName, goName(memberName))
}

func sortedEnumNames(values map[string]int64) []string {
	names := make([]string, 0, len(values))
	for name := range values {
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool {
		vi, vj := values[names[i]], values[names[j]]
		if vi == vj {
			return names[i] < names[j]
		}
		return vi < vj
	})
	return names
}

func goName(name string) string {
	parts := strings.Split(name, ".")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			b.WriteString(part[1:])
		}
	}
	return b.String()
}
