// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.
// Source: TwinCAT PLC symbols

package main

// MAINArrayOfStructs represents TwinCAT array type ARRAY [1..5] OF NUMBA
// Symbol: MAIN.ArrayOfStructs
type MAINArrayOfStructs [5]NUMBA

// TESTE represents TwinCAT enum TESTE
type TESTE int16

const (
	TESTE_Enum_member TESTE = 0
	TESTE_Blarhg TESTE = 1
)

// NUMBA represents TwinCAT type NUMBA
// Symbol: MAIN.ArrayOfStructs[4]
type NUMBA struct {
	More ads.Float64 `ads:"More"`
	Dizasta TESTE `ads:"Dizasta"`
	Bleeks ads.Uint32 `ads:"bleeks"`
	Moar TestStruct `ads:"moar"`
}

// TestStruct represents TwinCAT type TestStruct
// Symbol: MAIN.ArrayOfStructs[4].moar
type TestStruct struct {
	I ads.Int16 `ads:"i"`
	B ads.Float32 `ads:"b"`
	Test_array_st [13]ads.Float64 `ads:"test_array_st"`
}

