// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.
// Source: TwinCAT PLC symbols

package main

// MAINArrayOfStructs represents TwinCAT array type ARRAY [1..5] OF NUMBA
// Symbol: MAIN.ArrayOfStructs
type MAINArrayOfStructs [5]NUMBA

// TESTE represents TwinCAT enum TESTE
type TESTE int16

const (
	TESTE_Enum_member TESTE = 0
	TESTE_Blarhg TESTE = 1
)

