// Code generated by TwinCAT Go Code Generator. DO NOT EDIT.
// Source: TwinCAT PLC symbols

package main

// MAINTheetest represents TwinCAT TESTE variable
// Symbol: MAIN.theetest
type MAINTheetest TESTE

// TESTE represents TwinCAT enum TESTE
type TESTE int16

const (
	TESTE_Enum_member TESTE = 0
	TESTE_Blarhg TESTE = 1
)

